version: "3"
services:
  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    ports:
      - "5567:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=yourApi
